on: [push, pull_request]

name: ci

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Update package repository
        run: sudo apt update
      - name: Install packages
        run: |
          sudo apt clean
          sudo apt install -y build-essential libssl-dev nodejs

      - name: Install wrangler
        run: |
          wget https://github.com/cloudflare/wrangler/releases/download/v1.19.7/wrangler-v1.19.7-x86_64-unknown-linux-musl.tar.gz
          tar -xzf ./wrangler-v1.19.7-x86_64-unknown-linux-musl.tar.gz
          sudo cp ./dist/wrangler /usr/local/bin

      - name: Install wasmpack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      